-- PLANTIA AGRODATA - Estrutura Oracle (Fase 3)
CREATE TABLE PLANTIA_AGRODATA_SENSOR_DATA (
    ID_REGISTRO NUMBER(38,0) PRIMARY KEY,
    TIMESTAMP DATE,
    NITROGENIO NUMBER(38,0),
    FOSFORO NUMBER(38,0),
    POTASSIO NUMBER(38,0),
    PH_SOLO NUMBER(38,0),
    UMIDADE NUMBER(38,0),
    TEMPERATURA NUMBER(38,0),
    STATUS_BOMBA VARCHAR2(26 BYTE),
    RECOMENDACAO VARCHAR2(128 BYTE)
);

COMMENT ON TABLE PLANTIA_AGRODATA_SENSOR_DATA IS
'Dados de sensores simulados - PlantIA Agrodata (Fase 3).';

CREATE INDEX IDX_PLANTIA_TS ON PLANTIA_AGRODATA_SENSOR_DATA(TIMESTAMP);
CREATE INDEX IDX_PLANTIA_UMID ON PLANTIA_AGRODATA_SENSOR_DATA(UMIDADE);
CREATE INDEX IDX_PLANTIA_PH ON PLANTIA_AGRODATA_SENSOR_DATA(PH_SOLO);
