-- Consultas principais de validação - PlantIA Agrodata (Fase 3)

-- 1) Total de registros
SELECT COUNT(*) AS TOTAL_REGISTROS
FROM PLANTIA_AGRODATA_SENSOR_DATA;

-- 2) Amostra de dados
SELECT *
FROM PLANTIA_AGRODATA_SENSOR_DATA
FETCH FIRST 20 ROWS ONLY;

-- 3) Estatísticas simples
SELECT
    ROUND(AVG(UMIDADE), 2) AS UMIDADE_MEDIA,
    ROUND(AVG(PH_SOLO), 2) AS PH_MEDIO,
    ROUND(AVG(TEMPERATURA), 2) AS TEMP_MEDIA
FROM PLANTIA_AGRODATA_SENSOR_DATA;

-- 4) Contagem por status da bomba
SELECT STATUS_BOMBA, COUNT(*) AS TOTAL
FROM PLANTIA_AGRODATA_SENSOR_DATA
GROUP BY STATUS_BOMBA;

-- 5) Última leitura
SELECT *
FROM PLANTIA_AGRODATA_SENSOR_DATA
ORDER BY TIMESTAMP DESC
FETCH FIRST 1 ROW ONLY;
